name: cxhelper-oss-x64

on:
  workflow_dispatch:
    branch: master

jobs:
  build:
    name: 编译构建
    runs-on: ubuntu-latest
    container: linuxdeepin/deepin:crimson-amd64-v1.6.0

    steps:
    - name: 检查代码
      uses: actions/checkout@v4

    - name: 安装所需依赖
      run: |
        apt update && apt upgrade -y
        apt install -y \
          build-essential git python3-pip cmake make libx11-dev

    - name: 下载并解压头文件
      run: |
        curl -fsSL "https://nodejs.org/dist/v22.21.1/node-v22.21.1-headers.tar.gz" -o /tmp/node-headers.tar.gz
        tar -xzvf /tmp/node-headers.tar.gz -C /usr/local/ --strip-components=1

    - name: 编译
      continue-on-error: false
      run: |
        cmake -B build -DNODE_HEADERS_DIR=/usr/local/include/node -DCMAKE_BUILD_TYPE=Release
        cmake --build build -j 8

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: cxhelper-oss-x64
        path: ./build
